[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "parquest"
version = "0.0.12"
authors = [
    { name="Zaid Waqi", email="zaidwaqi@gmail.com" },
]
description = "A command line application that helps converting raw data into highly-structured data in Parquet."
readme = "README.md"
license = {text = "GPLv3"}
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/zaidwaqi/parquest"
Issues = "https://github.com/pypa/zaidwaqi/heyyou/parquest"

[project.scripts]
parquest = "parquest.main:cli"
