[tool.poetry]
name = "fastapi-overrider"
version = "0.5.0"
description = "FastAPI Dependency overrides made easy."
authors = ["Philipp Hack <philipp.hack@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/phha/fastapi-overrider"
repository = "https://github.com/phha/fastapi-overrider"
packages = [{include = "fastapi_overrider"}]
keywords = ["fastapi", "pytest"]
classifiers = [
    "Framework :: FastAPI",
    "Framework :: Pytest"
]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pre-commit = "^2.21.0"
isort = "^5.10.1"
pyproject-flake8 = "^4.0.1"
black = "^23.3.0"
ruff = "^0.1.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["ALL"]
ignore = ["D", "ANN101", "TRY003", "COM812", "ISC001"]
target-version = "py312"
fixable = ["ALL"]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]
