[project]
name = "sotrans_fastapi_keycloak"
authors = [
    { name = "Jonas Scholl", email = "jonas@code-specialist.com" },
    { name = "Yannic Schröer", email = "yannic@code-specialist.com" }
]
maintainers = [
    { name = "Jonas Scholl", email = "jonas@code-specialist.com" },
    { name = "Yannic Schröer", email = "yannic@code-specialist.com" }
]
readme = "README.md"
keywords = ['Keycloak', 'FastAPI', 'Authentication', 'Authorization']
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Internet :: WWW/HTTP :: Session',
    'Topic :: Internet :: WWW/HTTP :: WSGI',
    'Topic :: Software Development :: Libraries :: Application Frameworks',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Framework :: FastAPI',
    'License :: OSI Approved :: Apache Software License',
    'Programming Language :: Python :: 3.10',
]
requires-python = ">=3.10"
dependencies = [
    "certifi==2023.7.22",
    "charset-normalizer==3.2.0",
    "fastapi==0.100.1",
    "idna==3.4",
    "python-jose==3.3.0",
    "pydantic >= 2.3.0, < 3.0",
    "requests==2.31.0",
    "sniffio==1.3.0",
    "starlette==0.27.0",
    "typing_extensions==4.7.1",
    "urllib3==2.0.4"
]
version = "1.1.0"
