[project]
name = "chrome-switcher"
dependencies = [
  "chime; platform_system != 'Windows'",
  "pywin32; platform_system == 'Windows'",
]
version = "0.0.2"
authors = [
  { name="pilgrim_tabby", email="pilgrimtabby@gmail.com" },
]
description = "Easily create and load new Chrome profiles"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
]

[project.urls]
Homepage = "https://github.com/pilgrimtabby/chrome-switcher"
Issues = "https://github.com/pilgrimtabby/chrome-switcher/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
cswitch = "chrome_switcher.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/chrome_switcher"]
