[project]
name = "avilla-twilight"
version = "0.3.0"
authors = [
    { name = "GreyElaina", email = "GreyElaina@outlook.com" },
    { name = "BlueGlassBlock", email = "blueglassblock@outlook.com" },
    { name = "ProgramRipper", email = "programripper@foxmail.com" },
    { name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com" },
]
dependencies = [
    "avilla-core >= 1.0.0a8",
    "pydantic >= 1.10.0",
]
description = "Twilight Message Parser for Avilla"
requires-python = ">=3.9"

[project.license]
text = "AGPL-3.0"

[project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"

[build-system]
requires = [
    "mina-build>=0.5.1",
]
build-backend = "mina.backend"

[tool.pdm.build]
includes = [
    "avilla/twilight",
    ".mina/twilight.toml",
]

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.7.0",
    "mina-build>=0.4.0",
    "richuru>=0.1.1",
    "ruff>=0.0.272",
    "uvicorn>=0.22.0",
    "devtools>=0.11",
    "ipykernel>=6.23.2",
    "pip>=23.2.1",
    "pdm-mina>=0.3.1",
]

[tool.mina]
enabled = true

[tool.black]
include = "\\.pyi?$"
line-length = 120
target-version = [
    "py39",
]

[tool.isort]
profile = "black"
