[build-system]
requires = ["setuptools>=58.2.0", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pymox"
dynamic = ["version"]

[tool.poetry]
name = "pymox"
description = "Mock object framework"
packages = [
    {include = "mox"},
    {include = "mox/testing"}
]
version = "1.2.2"
authors = ["Ivan Neto <ivan.cr.neto@gmail.com>"]
license = "Apache License, Version 2.0"
homepage = "http://pymox.rtfd.io"
repository = "https://github.com/ivancrneto/pymox"
classifiers = [
    "Environment :: Console",
    "Development Status :: 5 - Production/Stable",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Utilities"
]
keywords = [
    "mox", "mock", "test", "mocking", "unittest", "pymox",
]
readme = "README.rst"

[tool.poetry.dependencies]
setuptools_scm = { version = "^8.0", python = ">=3.8,<4" }
python = ">=3.5, <4"

[tool.poetry.group.dev.dependencies]
pytest = [
    {version = "^3.2", python = "<3.6"},
    {version = "^6.1", python = "==3.6"},
    {version = "^7.1", python = ">=3.7"}
]
pytest-cov = [
    {version = "^2.5", python = "<3.6"},
    {version = "^3.0", python = "==3.6"},
    {version = "^4.0", python = ">=3.7"}
]
coverage = [
    {version = "^4.5", python = "<3.6"},
    {version = "^6.1", python = "==3.6"},
    {version = "^7.2", python = ">=3.7"}
]

[tool.setuptools_scm]
write_to = "mox/__version__.py"

[tool.pytest]
addopts = [
    "-v",
    "--cov-config",
    ".coveragerc",
    "--cov=mox",
    "--cov-branch",
    "--cov-report",
    "term-missing",
    "test/mox_test.py"
]


[tool.black]
line-length = 120
target-version = [ "py35" ]


[tool.isort]
atomic = true
case_sensitive = true
filter_files = true
import_heading_firstparty = "Internal imports"
import_heading_stdlib = "Python imports"
import_heading_thirdparty = "Pip imports"
known_startup = [
  "startup",
]
line_length = 120
lines_after_imports = 2
profile = "black"
py_version = "auto"
remove_redundant_aliases = true
sections = [
  "FUTURE",
  "STARTUP",
  "STDLIB",
  "THIRDPARTY",
  "FIRSTPARTY",
  "LOCALFOLDER",
]

[tool.bandit.assert_used]
excludes = ['*_test.py', '*/test_*.py']
