[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "secret-agent"
version = "23.12.2503"
authors = [
  { name="ghostdisco", email="pypi@ghostdisco.me" },
]
description = "An agent for handling secrets in config"
readme = "README.md"
requires-python = ">=3.8.1"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dependencies = [
  "cryptography>=41.0.7"
]

[project.urls]
Homepage = "https://github.com/ghostdisco/secret-agent"
Issues = "https://github.com/ghostdisco/secret-agent/issues"