[project]
name = "yuanpypi"
version = "0.0.3"
authors = [
  { name="Tiezheng Yuan", email="tiezhengyuan@hotmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Tiezhengyuan/yuan_pypi"
Issues = "https://github.com/Tiezhengyuan/yuan_pypi/issues"

