[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vec2tif"
description = "Conversion of vector data to GeoTIFF"
readme = "README.md"
requires-python = ">=3.7"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
version = "0.2.0"
authors = [
    { name="Kiwamu Ishikura", email="ishikura.kiwamu@gmail.com" }
]
dependencies = [
    "numpy",
    "gdal",
    "shapely",
    "pyproj",
    "rasterio",
    "geopandas",
    "haversine"
]

[project.optional-dependencies]
dev = [
    "build",
    "twine",
]
