[tool.poetry]
name = "pathlibutil"
version = "0.1.0"
description = ""
authors = ["Christoph DÃ¶rrer <d-chris@web.de>"]
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
]
keywords = ["pathlib", "hashlib"]
repository = "https://github.com/d-chris/pathlibutil"

[tool.poetry.dependencies]
python = ">=3.8,<3.13"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
tox = "^4.11.4"
pytest-random-order = "^1.1.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38,py39,py310,py311,py312

[testenv]
deps =
    pytest
    pytest-random-order
    pytest-mock
    pytest-cov
commands = pytest --random-order
"""

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = "tests"
addopts = "--random-order --cov=pathlibutil --cov-report=term-missing:skip-covered --color=yes"
