[tool.poetry]
name = "WebtoonScraper"
version = "2.3.4"  # This version will be matched when build.py is run.
description = "Scraping webtoons with ease."
authors = ["ilotoki0804 <ilotoki0804@gmail.com>"]
license = "MIT"
readme = "README_build.md"
keywords = ["Webtoon", "Webtoon Scraper", "Naver Webtoon", "Webtoon Downloader", "Download Webtoon"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    # "Programming Language :: Python :: 3.12",
]

[tool.poetry.urls]
Homepage = "https://ilotoki0804.gitbook.io/webtoonscraper/"
Documentation = "https://github.com/ilotoki0804/WebtoonScraper"
Repository = "https://github.com/ilotoki0804/WebtoonScraper"
Issues = "https://github.com/ilotoki0804/WebtoonScraper/issues"
Changelog = "https://github.com/ilotoki0804/WebtoonScraper#relese-note"

[tool.poetry.scripts]
WebtoonScraper = "WebtoonScraper:__main__.main"
webtoon = "WebtoonScraper.__main__:main"

[tool.poetry.dependencies]
python = "^3.10"
tqdm = "^4.66.1"
typing-extensions = "^4.8.0"
rich = "^13.6.0"
demjson3 = "^3.0.6"
Pillow = "^10.0.1"
pyfilename = "^0.4.0"
resoup = "==0.5.2"

[tool.poetry.group.dev.dependencies]
tomlkit = "^0.12.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
