[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "etautil"
requires-python = ">3.10"
dynamic = ["version", "description"]
readme = "README_pypi.md"
license= {file = "LICENSE"}
authors = [
    {name = "Ella Jameson", email = "ellagjameson@gmail.com"}
]

classifiers = []
dependencies = [
    "pydantic",
    "pendulum"
]

[project.urls]
homepage = "https://github.com/nimaid/etautil"
repository = "https://github.com/nimaid/etautil"
issues = "https://github.com/nimaid/etautil/issues"
