[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "DataQualityFrameworkGovernance"
version = "1.0.0.1"
authors = [
  { name="Rajith Prabhakaran", email="rajith.prabhakaran@yahoo.com" },
]

description = "Data Quality Framework Governance is a structured approach to assessing, monitoring, and improving the quality of data."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"DQ Framework Design" = "https://github.com/RajithPrabakaran/DataQualityFrameworkGovernance/blob/main/DataQualityFrameworkGovernance.png"
"Homepage" = "https://github.com/RajithPrabakaran/DataQualityFrameworkGovernance"
"Bug Tracker" = "https://github.com/RajithPrabakaran/DataQualityFrameworkGovernance/issues"
"Github Documentation" = "https://github.com/RajithPrabakaran/DataQualityFrameworkGovernance"