name: Run pytest âœ…

on:
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11']

    steps:
    - name: check out repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true

    - name: Set up micromamba ðŸ
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yaml
        cache-environment: true

    - name: Set up Python ðŸ ${{ matrix.python }}
      run: |
        micromamba install -y python=${{ matrix.python }}
      shell: micromamba-shell {0}


    - name: Build & Install package ðŸ“¦
      run: |
        python dev.py build
        python dev.py install
      shell: micromamba-shell {0}

    # pytest -> JUnit xml format
    - name: Execute pytest âœ…
      run: |
        python -m pytest --junit-xml results/pytest.xml
      shell: micromamba-shell {0}
      continue-on-error: true

    - name: Upload PyTest Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: PyTest Results (Python ${{ matrix.python }})
        path: results/*.xml

    - name: Download Artifacts
      if: success() || failure()
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        junit_files: artifacts/**/*.xml
