[project]
name = "Chaparral"
version = "0.0.11"
authors = [
    { name="Edgar Andrade-Lotero", email="andradeed78@gmail.com" },
    { name="Alejandro Andrade-Lotero", email="landrad78@gmail.com" },
]
description = "Recomienda rutas"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
]
dependencies = [
    "gymnasium==0.28.1",
    "ipython==7.19.0",
    "jsonlines==4.0.0",
    "matplotlib==3.7.1",
    "networkx==2.7.1",
    "numpy==1.24.2",
    "pandas==1.5.3",
    "plotly==5.18.0",
    "polars==0.20.2",
    "prettytable==3.9.0",
    "seaborn==0.13.0",
    "termcolor==1.1.0",
    "torch==1.12.0",
    "tqdm==4.65.0",
    "typer==0.9.0",
]
[project.urls]
Homepage = "https://github.com/ardillabyte/chaparral"

[tool.setuptools.packages.find]
where = ["src"]
