[tool.poetry]
name = "xerra"
version = "0.1.5"
description = "CLI tool for downloading and converting CFT datasets"
authors = ["Eli White <eli.white@emitimaging.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
mhdwriter = "^0.1.9"
click = "^8.1.7"
tqdm = "^4.66.1"
loguru = "^0.7.2"
aiohttp = "^3.9.1"


[tool.poetry.scripts]
xerra = "xerra.cli:main"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
