[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "geneplore_bare_api"
version = "3.6.0"
authors = [
  { name="thegamebegins25", email="will@geneplore.com" },
]
description = "The bare API for Geneplore AI's API. Don't use this library directly, use geneplore_api instead after signing up at https://geneplore.com ."
readme = "README.md"
requires-python = ">=3.7"

dependencies=[
    'requests',
    'pandas',
    'google-api-python-client',
    'google-api-core',
    'python-dotenv',
    'boto3'
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha"
]

[project.urls]
"Homepage" = "https://github.com/GeneploreAI/geneplore-api"
"Bug Tracker" = "https://github.com/GeneploreAI/geneplore-api/issues"