[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "onecondition"
dynamic = ["version", "description"]
readme = "README_pypi.md"
license= {file = "LICENSE"}
authors = [
    {name = "Ella Jameson", email = "ellagjameson@gmail.com"}
]

classifiers = []
dependencies = []

[project.urls]
homepage = "https://github.com/nimaid/python-onecondition"
repository = "https://github.com/nimaid/python-onecondition"
documentation = "https://onecondition.readthedocs.io/en/latest/index.html"
issues = "https://github.com/nimaid/python-onecondition/issues"

[project.scripts]
onecondition = "onecondition:run"
