[tool.poetry]
name = "k3im"
version = "0.0.8"
description = ""
authors = ["Muhammad Anas Raza <memanasraza@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
keras = ">=3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
