[tool.poetry]
name = "webdriver-browser"
version = "0.1.0.dev1"
description = "More convenient methods for creating multiple selenium browsers."
authors = ["Invoker Bot <invoker-bot@outlook.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
selenium = "^4.16.0"
selenium-wire = "^5.1.0"
webdriver-manager = "^4.0.1"
undetected-chromedriver = "^3.5.4"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
flake8 = "^6.1.0"
pylint = "^3.0.3"
mock = "^5.1.0"
freezegun = "^1.4.0"
pproxy = "^2.7.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
