[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "calculator_sf"
authors = [{name = "Shanti Flagg", email = "shanti.flagg@gmail.com"}]
version = "0.1.0"
description = "a simple calculator"
readme = "README.txt"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]

[project.urls]
Home = "https://github.com/TuringCollegeSubmissions/sflagg-DWWP.1.5"
